apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-cm
  labels:
    name: fluentd-cm
  namespace: default
data:
  fluentd.conf: |-
    <source>
      @type forward
      port 24224
      bind 0.0.0.0
    </source>
    <match terraform>
      @type stdout
    </match>
